### ISSUE TITLE
Changing the default core doesn't apply as the default for roms not in the RDB, it is forced to interpreter, same applies to SMC.

### ISSUE THREAD

**Issue by BruceShankleIV** [pj64team/Project64-1.6-Plus#21]
If a user sets the default core style from interpreter to recompiler in the advanced tab, when opening a rom that isn't located in the RDB, it will use interpreter anyways. This is a regression from OG PJ64 1.6 which allowed users to do that. Solution would be making it so that the rom settings window is set to "default". The SMC (self-modifying code method) is also forced to check mem advance and ignores the default setting and should be able to fixed the same way. This way users have the option to modify defaults to cater to romhacks they play like SM64 with Cache/recompiler/CF1.

**Comment by TheGent** [comment]
we will leave stuff like this you or anyone else picking up the project, as the default was override to allow for better not in database compact.

**Comment by TheGent** [comment]
Ok I have reset everything back to Default, it is now ready for anyone to change what they desire once the release happens.
