### ISSUE TITLE
Star Manager compatibility

### ISSUE THREAD

**Issue by GlitchyDorime** [pj64team/Project64-1.6-Plus#29]
[Star Display](https://github.com/aglab2/SM64StarDisplay) is a program that reads SM64's memory trough the emulator and depending of that memory, it will display which stars, keys, red coins, and more have been collected, it's pretty useful for playing any SM64 Rom-Hacks.

![Screenshot_7](https://github.com/user-attachments/assets/a35f853f-cb65-437e-9466-050c86f22932)
![Screenshot_6](https://github.com/user-attachments/assets/b05b0301-7cdf-4784-b4de-b80ae5729b47)
First screenshot is how it should look when it connects using the original Project64 1.6
Second screenshot shows that Star Display doesn't connect with Project64 1.6 Plus

As a suggestion, having Star Display be able to connect with this version of the emulator would be pretty nice.

**Comment by GlitchyDorime** [comment]
Star Display not being able to recognize the emulator happens due to the executable file being named anything else that isn't specifically "Project64.exe", changing it allows that display to correctly communicate with the emulator, recommend changing the executable name back to Project64.exe for later updates/revisions.

**Comment by TheGent** [comment]
> Star Display not being able to recognize the emulator happens due to the executable file being named anything else that isn't specifically "Project64.exe", changing it allows that display to correctly communicate with the emulator, recommend changing the executable name back to Project64.exe for later updates/revisions.

This is not an issue with PJ64 1.6 Plus as it is named that for a reason and not likely to be renamed in the future. This is an issue with Aglab2's Star Display not supporting it. I suggest asking him to do so.

**Comment by TheGent** [comment]
Closing as no reply and is not a Project issue but an external app issue.
